# See LICENSE file in the project root for license information.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstream-operator-controller-manager
  namespace: rstream-system
  labels:
    app.kubernetes.io/name: rstream-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: rstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rstream-operator
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rstream-operator
        app.kubernetes.io/component: manager
        app.kubernetes.io/part-of: rstream
    spec:
      serviceAccountName: rstream-operator-controller-manager
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: controller:latest
          imagePullPolicy: IfNotPresent
          args:
            - --leader-elect
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      terminationGracePeriodSeconds: 10
