apiVersion: v2
name: rstream-operator
description: Kubernetes operator for managing rstream tunnels
type: application
version: 0.5.1
appVersion: 0.5.1
kubeVersion: '>=1.29.0-0'
icon: https://rstream.io/images/brand/rstream-logo-square-dark.png
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: Apache-2.0
keywords:
  - rstream
  - tunnels
  - operator
home: https://rstream.io
sources:
  - https://github.com/rstreamlabs/rstream-operator
maintainers:
  - name: rstream
    email: support@rstream.io
