apiVersion: v2
name: rstream-operator
description: Kubernetes operator for managing rstream tunnels
type: application
version: 0.2.3
appVersion: 0.2.3
kubeVersion: '>=1.29.0-0'
keywords:
  - rstream
  - tunnels
  - operator
home: https://rstream.io
sources:
  - https://github.com/rstreamlabs/rstream-operator
maintainers:
  - name: rstream
    email: support@rstream.io
