# See LICENSE file in the project root for license information.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rstream-operator-manager-rolebinding
  labels:
    app.kubernetes.io/name: rstream-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: rstream
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: rstream-operator-controller-manager
    namespace: rstream-system
