apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rstream-operator.fullname" . }}
  labels:
    {{- include "rstream-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
